project:
  type: website

website:
  title: "Justin Kracht"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JustinKracht
      - icon: linkedin
        href: linkedin.com/in/justinkracht/
format:
  html:
    theme: simplex
    css: styles.css

editor: source

