# Illustrates "why do we escape the elliptope": pairwise-complete-data
# sample correlations from a small, MCAR-missing trivariate normal sample
# can land outside the elliptope even though the true population matrix is
# comfortably inside it. Used by src/content/research/elliptope.mdx.
#
# Run with:  Rscript data-gen/elliptope-escape.R
# Writes:    public/data/elliptope-escape.json
#
# NOTE: the committed JSON was generated by an equivalent Node script (same
# algorithm: Cholesky-correlated normals, MCAR missingness, pairwise
# deletion), not by executing this file, since R wasn't available in the
# environment this was built in. R's RNG stream differs from Node's, so
# re-running this script will reproduce the same *qualitative* pattern
# (roughly a quarter of replications escaping) but not the exact same points.

library(jsonlite)

set.seed(20260702)

true_rho <- 0.75
n_subjects <- 10
n_replications <- 90
missing_prob <- 0.4

L <- chol(matrix(true_rho, 3, 3) + diag(1 - true_rho, 3))  # upper Cholesky; R's chol() returns upper-triangular

pairwise_cor <- function(a, b) {
  keep <- !is.na(a) & !is.na(b)
  if (sum(keep) < 3) return(NA)
  suppressWarnings(cor(a[keep], b[keep]))
}

points <- list()
for (rep in seq_len(n_replications)) {
  z <- matrix(rnorm(n_subjects * 3), nrow = n_subjects, ncol = 3)
  x <- z %*% L  # rows ~ N(0, R) with R = true equicorrelation matrix

  x1 <- x[, 1]
  x2 <- ifelse(runif(n_subjects) < missing_prob, NA, x[, 2])
  x3 <- ifelse(runif(n_subjects) < missing_prob, NA, x[, 3])

  r12 <- pairwise_cor(x1, x2)
  r13 <- pairwise_cor(x1, x3)
  r23 <- pairwise_cor(x2, x3)
  if (any(is.na(c(r12, r13, r23)))) next

  det <- 1 + 2 * r12 * r13 * r23 - r12^2 - r13^2 - r23^2
  points[[length(points) + 1]] <- list(
    r12 = round(r12, 3),
    r13 = round(r13, 3),
    r23 = round(r23, 3),
    valid = det >= -1e-9
  )
}

write_json(
  list(
    trueRho = true_rho,
    nSubjects = n_subjects,
    missingProb = missing_prob,
    seed = 20260702,
    points = points
  ),
  "public/data/elliptope-escape.json",
  auto_unbox = TRUE,
  digits = 6
)
